### ISSUE TITLE
generator crashes when sees bitfield structs

### ISSUE THREAD

**Issue by pioupus** [Crystal-Photonics/RPC-Generator#17]
for example:
typedef struct{
    int16_t temperature_thermocuouple;
    int16_t temperature_coldjunction;

```
unsigned int fault:1;
unsigned int   scvFault:1;
unsigned int   scgFault:1;
unsigned int   ocFault:1;
```

}max33185result_t;

**Comment by pioupus** [comment]
also crashes with 

```
#ifdef __cplusplus
extern "C" {
#endif /* __cplusplus */
#include <stdint.h>


typedef struct{
    int16_t temperature_thermocuouple;
    int16_t temperature_coldjunction;

    int8_t fault;
    int8_t scvFault;
    int8_t scgFault;
    int8_t ocFault;

}max33185result_t;

#pragma RPC prefix RPC_TRANSMISSION_

#pragma RPC noanswer qtUpdateRealTemperature
    void qtUpdateRealTemperature(uint16_t data,  max33185result_t result);
#ifdef __cplusplus
}
#endif /* __cplusplus */

```

as server.h

```
Warning: #include file "stdint.h" not found, skipping
Traceback (most recent call last):
  File "../../../RPC-Generator/RPC-gen.py", line 1680, in <module>
    rpcHeader, rpcImplementation, requestParserImplementation, answerParser, answerSizeChecker, documentation = generateCode(files["ServerHeader"], root, relpath(files["SERVER_GENINCDIR"], files["SERVER_SRCDIR"]), relpath(files["ServerHeader"], files["SERVER_SRCDIR"]))
  File "../../../RPC-Generator/RPC-gen.py", line 1314, in generateCode
    rpcImplementation = "\n".join(f.getDefinition() for f in functionlist)
  File "../../../RPC-Generator/RPC-gen.py", line 1314, in <genexpr>
    rpcImplementation = "\n".join(f.getDefinition() for f in functionlist)
  File "../../../RPC-Generator/RPC-gen.py", line 603, in getDefinition
    inputParameterSerializationCode = "".join(p["parameter"].stringify(p["parametername"], 1) for p in self.parameterlist if p["parameter"].isInput()),
  File "../../../RPC-Generator/RPC-gen.py", line 603, in <genexpr>
    inputParameterSerializationCode = "".join(p["parameter"].stringify(p["parametername"], 1) for p in self.parameterlist if p["parameter"].isInput()),
  File "../../../RPC-Generator/RPC-gen.py", line 494, in isInput
    raise NotImplemented
TypeError: exceptions must derive from BaseException

```

**Comment by pioupus** [comment]
workaround:

```
#ifdef __cplusplus
extern "C" {
#endif /* __cplusplus */
#include <stdint.h>


typedef struct{
    int16_t temperature_thermocuouple;
    int16_t temperature_coldjunction;

    int8_t fault;
    int8_t scvFault;
    int8_t scgFault;
    int8_t ocFault;

}max33185result_t;

#pragma RPC prefix RPC_TRANSMISSION_

#pragma RPC noanswer qtUpdateRealTemperature
    //void qtUpdateRealTemperature(uint16_t data,  max33185result_t result_inout[1]);
    void qtUpdateRealTemperature(uint16_t data,  max33185result_t result_in[1]);
#ifdef __cplusplus
}
#endif /* __cplusplus */
```

**Comment by pioupus** [comment]
structs by value dont work. Only by reference woks
